export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";
export const REQUEST_HEROES_PENDING = "REQUEST_HEROES_PENDING";
export const REQUEST_HEROES_SUCCESS = "REQUEST_HEROES_SUCCESS";
export const REQUEST_HEROES_FAILED = "REQUEST_HEROES_FAILED";
export const TRIGGER_CLICK = "TRIGGER_CLICK";
